### PR TITLE
Event.url field + Referrer header

### PR DESCRIPTION
**Pull request by nikitakasatkin44**
Added new **url** field for io.jenkins.plugins.generic.event.Event
Added "Referrer" header for case when required to distinguish several Jenkins instances

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by ant1dot** [comment]
@JohnNiang can you accept or give feedback?

**Comment by JohnNiang** [comment]
> @JohnNiang can you accept or give feedback?

Sorry for the lack of response. I will take some time to review this PR recently. Please wait for a moment.

**Review by JohnNiang — APPROVED** [review]
Thanks for your contribution!

LGTM

**Comment by ant1dot** [comment]
@JohnNiang can you merge pr and deploy release?

**Comment by ant1dot** [comment]
@JohnNiang Hello! Can you deploy the package? [cd failed](https://github.com/jenkinsci/generic-event-plugin/runs/8988258688)

**Comment by JohnNiang** [comment]
> 

Thank you for reminding me! I'm trying to fix it.

**Comment by JohnNiang** [comment]
Hi @ant1dot , the CD has been run successully, please see <https://github.com/jenkinsci/generic-event-plugin/actions/runs/3327734111/jobs/5502911312#step:4:176> and <https://github.com/jenkinsci/generic-event-plugin/releases/tag/40.v080de468d609>.

**Comment by ant1dot** [comment]
> 

Great! Thank you!

**Pull request merged**
